require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks! :linkage => :static
install! 'cocoapods', :disable_input_output_paths => true


# 👉 use our own function name to avoid any override
def my_capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  # IMPORTANT: point to your local, version-controlled copy
  pod 'CapacitorFirebaseAnalytics', :path => '../LocalPods/CapacitorFirebaseAnalytics'
  pod 'CapacitorFirebaseAuthentication', :path => '../../node_modules/@capacitor-firebase/authentication'
end

target 'App' do
  my_capacitor_pods
  pod 'Firebase/Analytics'     # keep Firebase available in the app target too
end

post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -ObjC'
    end
  end
  installer.aggregate_targets.each do |agg|
    agg.user_project.native_targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
  end
end
