source "https://rubygems.org"

# Use bleeding-edge CocoaPods/Xcodeproj that support Xcode 16 (object version 70)
gem "cocoapods", git: "https://github.com/CocoaPods/CocoaPods.git", branch: "master"
gem "xcodeproj", git: "https://github.com/CocoaPods/Xcodeproj.git", branch: "master"
RUBY